Homework1
made-ml-in-prod-2022/julia_korpusova pull request #1
Opened 2022-05-14 20:05 UTC by julia-kv

Homework 1

2022-05-19 19:00 UTC, nickdndev requested changes

2022-05-19 19:00 UTC, nickdndev commented on ml_project/train_pipeline.py
> +    # if downloading_params:
remove unused code

2022-05-19 19:00 UTC, nickdndev commented on requirements.txt
> +PyYAML
add version for deps

2022-05-19 19:00 UTC, nickdndev commented on ml_project/test/test_model_predict.py
> +    df.drop(columns=features.target_col)
add metrics validation(delta +-5-10%)

2022-05-19 19:00 UTC, nickdndev commented on ml_project/train_pipeline.py
> +#                     format="%(pasctime)s\t%(levelname)s\t%(message)s",
remove unused code

2022-05-19 19:02 UTC, nickdndev commented
Общ.вопросы:
1. добавить в гит игнор кеш питон , чтобы он не ушел в мастер ветку

2022-06-14 13:46 UTC, julia-kv commented on ml_project/train_pipeline.py
> +#                     format="%(pasctime)s\t%(levelname)s\t%(message)s",
Здравствуйте! Скжаите, пожалуйста, можно заливать в главную ветку дз?

2022-06-17 12:53 UTC, nickdndev commented
score: 22*0.6=13

2022-06-17 12:53 UTC, merged